-- MySQL Script generated by MySQL Workbench
-- Sun Mar 10 18:05:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SistemaCadastro_FullstackMaster
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaCadastro_FullstackMaster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaCadastro_FullstackMaster` DEFAULT CHARACTER SET utf8 ;
USE `SistemaCadastro_FullstackMaster` ;

-- -----------------------------------------------------
-- Table `SistemaCadastro_FullstackMaster`.`PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaCadastro_FullstackMaster`.`PESSOA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(80) NOT NULL,
  `NASCIMENTO` DATE NULL,
  `CARGO` VARCHAR(145) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaCadastro_FullstackMaster`.`PROJETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaCadastro_FullstackMaster`.`PROJETO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `PESSOA_ID_DONO` INT NOT NULL,
  `PESSOA_ID_GERENTE` INT NOT NULL,
  PRIMARY KEY (`ID`, `PESSOA_ID_DONO`, `PESSOA_ID_GERENTE`),
  INDEX `fk_PROJETO_PESSOA_idx` (`PESSOA_ID_DONO` ASC),
  INDEX `fk_PROJETO_PESSOA1_idx` (`PESSOA_ID_GERENTE` ASC),
  CONSTRAINT `FK_PROJETO_PESSOA_DONO`
    FOREIGN KEY (`PESSOA_ID_DONO`)
    REFERENCES `SistemaCadastro_FullstackMaster`.`PESSOA` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PROJETO_PESSOA_GERENTE`
    FOREIGN KEY (`PESSOA_ID_GERENTE`)
    REFERENCES `SistemaCadastro_FullstackMaster`.`PESSOA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
